Synapsr/Controllers/SlackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Synapsr.Logistics;

namespace Synapsr.Controllers
{
    public class SlackController : Controller
    {
        private Slack.Webhooks.SlackClient scl = new Slack.Webhooks.SlackClient(AppVars.SlackWebHook);

        #region SerializationStructure
        public class Rootobject
        { 
            public List<Filename> filnames { get; set; }
        }

        public class Filename
        {
            public string currname { get; set; }
            public string initname { get; set; }
        }
        #endregion

        // GET: Slack
        public ActionResult Index()
        {
            var xx = Logistics.AccountManager.GetCurrentUser();
            switch (xx == null)
            {
                case true:
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.Unauthorized);
                case false:
                    if (xx.Item2.ElevationName != "Teacher")
                    {
                        return new HttpStatusCodeResult(System.Net.HttpStatusCode.Unauthorized);
                    }
                    break;
            }
            return View();
        }

        [HttpGet]
        public FileResult Download(string fileguid, string type)
        {
            string ext = System.IO.Path.GetExtension(fileguid);

            string filepath = "~/SlackStore/" + fileguid;
            var urf = Newtonsoft.Json.JsonConvert.DeserializeObject<Rootobject>(System.IO.File.ReadAllText(Server.MapPath("~/Content/Sett/json.json")));
            var ffff=urf.filnames.FirstOrDefault(u => u.currname == fileguid).initname;
            return File(filepath, type, ffff);
        }

        [HttpPost]
        public ActionResult Post(string message, HttpPostedFileBase file, string groupid,bool general=false)
        {
            if (!Directory.Exists(Server.MapPath("~/SlackStore/")))
                Directory.CreateDirectory(Server.MapPath("~/SlackStore/"));
            string filename = string.Empty;
            var curusr = Logistics.AccountManager.GetCurrentUser();
            if (file != null && curusr!=null)
            {
                
                var ext = Path.GetExtension(file.FileName);
                filename = Guid.NewGuid() + ext;
                file.SaveAs(Server.MapPath("~/SlackStore/" + filename));
                SaveConventions(filename, file.FileName);

                //Anunt general cu fisier.
                if (general)
                    scl.Post(new Slack.Webhooks.SlackMessage
                    {
                        Text = "Anunt:->  " +
                        message +
                        "  Fișier: " +
                        ResolveServerUrl(
                            VirtualPathUtility.ToAbsolute(
                                "~/Slack/Download/?fileguid=" +
                                filename +
                                "&type=" +
                                file.ContentType),
                            false) + "  De la: " +
                                curusr.Item1.FirstName + " " +
                                curusr.Item1.LastName,
                        Channel = "general"
                    });
                else
                    //Sarcina de laborator pentru grupa.
                    scl.Post(new Slack.Webhooks.SlackMessage
                    {
                        Text = message + ": " + ResolveServerUrl(VirtualPathUtility.ToAbsolute("~/Slack/Download/?fileguid=" + filename + "&type=" + file.ContentType), false) +
                                "  De la: " +
                                curusr.Item1.FirstName + " " +
                                curusr.Item1.LastName,
                        Channel = groupid.ToLower()
                    });
                ViewBag.status = "ok";
                return View("Index");
            }
            else
            {
                var usr = curusr.Item1;
                if (message == string.Empty)
                {
                    ViewBag.status = "err";
                    return View("Index");
                }
                else
                {
                    if (general)
                        //Anunt general fara fisier
                        scl.Post(new Slack.Webhooks.SlackMessage
                        {
                            Text = "Anunt:->  " + message + "  De la: " + usr.FirstName + " " + usr.LastName,
                            Channel = "general"
                        });
                    else
                        //Anunt pentru grupa fara fisier
                        scl.Post(new Slack.Webhooks.SlackMessage
                        {
                            Text = "Anunt:->  " + message + "  De la: " + usr.FirstName + " " + usr.LastName,
                            Channel = groupid.ToLower()
                        });
                    ViewBag.status = "ok";
                    return View("Index");
                }
            }
        }

        public void SaveConventions(string currentname,string initialname)
        {
            var jsonstring = System.IO.File.ReadAllText(Server.MapPath("~/Content/Sett/json.json"));
            var filnms = Newtonsoft.Json.JsonConvert.DeserializeObject<Rootobject>(jsonstring);
            filnms.filnames.Add(new Filename { currname = currentname, initname = initialname });
            var outp = Newtonsoft.Json.JsonConvert.SerializeObject(filnms, Newtonsoft.Json.Formatting.Indented);
            System.IO.File.WriteAllText(Server.MapPath("~/Content/Sett/json.json"), outp);
        }
        public static string ResolveServerUrl(string serverUrl, bool forceHttps)
        {
            if (serverUrl.IndexOf("://") > -1)
                return serverUrl;

            string newUrl = serverUrl;
            Uri originalUri = System.Web.HttpContext.Current.Request.Url;
            newUrl = (forceHttps ? "https" : originalUri.Scheme) +
                "://" + originalUri.Authority + newUrl;
            return newUrl;
        }
    }
}

Synapsr/Views/Shared/LoginFormPartial.cshtml
<div id="login-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Login</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="well">
                            @using (Html.BeginForm("Login", "Account", FormMethod.Post))
                            {
                                if (Request.QueryString["Err"] != null)
                                {
                                    switch (Request.QueryString["Err"])
                                    {
                                        case "nodata":
                                            <div class="alert alert-danger">
                                                Please provide username and password.
                                            </div>
                                            break;
                                        case "invusr":
                                            <div class="alert alert-danger">
                                                Invalid username or password.
                                            </div>
                                            break;
                                        default:
                                            <div class="alert alert-danger">
                                                This username does not exist.
                                            </div>
                                            break;
                                    }
                                }

                                <div class="form-group">
                                    @Html.Label("UserName", "Username")
                                    <input type="text" id="UserName" name="UserName" class="form-control" />
                                    <span class="help-block"></span>
                                </div>
                                    <div class="form-group">
                                        @Html.Label("Password", "Password")
                                        <input type="password" id="Password" name="Password" class="form-control" />
                                        <span class="help-block"></span>
                                    </div>
                                    <div id="loginErrorMsg" class="alert alert-error hide">Wrong username og password</div>
                                    <div class="row">
                                        <span class="help-block"></span>
                                        <div class="col-md-6">
                                            <button type="submit" class="btn btn-success btn-block">Login</button>
                                        </div>
                                        <span class="help-block"></span>
                                        <div class="col-md-6">
                                            <p>@Html.ActionLink("Register Now!", "Register", "Account", null, new { @class = "btn btn-info btn-block" })</p>
                                        </div>
                                    </div>
                            }
                            <span class="help-block"></span>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Synapsr/Views/Shared/_Layout.cshtml
@{
    DatabaseStore db = new DatabaseStore();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Content/favicon.ico" />
    <title>@ViewBag.Title - Catedra IA</title>
    @Styles.Render("~/bundles/styles/bootstrap")
    @Styles.Render("~/bundles/styles/local")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Informatica Aplicata", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("StructCat", "Home")">Structura Catedrei</a></li>
                    @{
                        var xx = Synapsr.Logistics.AccountManager.GetCurrentUser();
                        if (xx != null)
                        {
                            if (xx.Item2.ElevationName == "Teacher")
                            {
                                <li><a href="@Url.Action("Index", "Slack", null)">Slack</a></li>
                            }
                            <li><a href="@Url.Action("Index", "Organizr", null)">Orar</a></li>
                        }
                    }
                    <li>@Html.ActionLink("Istoric", "Timeline", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Html.Partial("LoginFormPartial")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">

        @if (Request.QueryString["Err"] != null)
        {
               @:$("#login-modal").modal("show");
        }
    </script>
</body>
</html>